# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Usetania"
license = "MIT"
licenselink = "https://github.com/Tanibox/usetania-static/blob/master/themes/usetania/LICENSE"
description = "A Hugo theme for the Tania official website."
homepage = "http://usetania.org/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Asep Bagja Priandana"
  homepage = "https://asepbagja.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
